/*  _________________________________________________________________________
 *
 *  MTGL: The MultiThreaded Graph Library
 *  Copyright (c) 2008 Sandia Corporation.
 *  This software is distributed under the BSD License.
 *  Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
 *  the U.S. Government retains certain rights in this software.
 *  For more information, see the README file in the top MTGL directory.
 *  _________________________________________________________________________
 */

/****************************************************************************/
/*! \file types.hpp

    \brief This file defines the sizes of the integer, long, and long long
           types and their unsigned counterparts.  It also includes
           inttypes.h.  Since MS Visual Studio before 2010 doesn't include
           inttypes.h, we include the versions for Windows provided by the
           msinttypes project.

    \author Greg Mackey (gemacke@sandia.gov)

    \date 3/14/2011

    We define the values manually for Windows systems.  All other systems
    are caught by including mtgl/mtgl_config.h which is generated by running
    autoreconf / configure.
*/
/****************************************************************************/

#ifndef MTGL_TYPES_HPP
#define MTGL_TYPES_HPP

#include <limits.h>

// Include inttypes.h if it exists.  If not, define the values that are
// normally defined by inttypes.h.  AFIK, inttypes.h is available everywhere
// except for MS Visual Studio.
#ifdef _WIN32
  #include <win32/inttypes.h>
#else
  #include <inttypes.h>
#endif

#if defined(_WIN64)
  // 64 bit Windows is LLP64.
  #define SIZEOF_INT 4
  #define SIZEOF_UNSIGNED 4
  #define SIZEOF_LONG 4
  #define SIZEOF_UNSIGNED_LONG 4
  #define SIZEOF_LONG_LONG 8
  #define SIZEOF_UNSIGNED_LONG_LONG 8
#elif defined(_WIN32)
  // 32 bit Windows is ILP32.
  #define SIZEOF_INT 4
  #define SIZEOF_UNSIGNED 4
  #define SIZEOF_LONG 4
  #define SIZEOF_UNSIGNED_LONG 4
  #define SIZEOF_LONG_LONG 4
  #define SIZEOF_UNSIGNED_LONG_LONG 4
#else
  // All other cases covered here.
  #include <mtgl/mtgl_config.h>
#endif

#endif
